#!/usr/bin/env python3
# Copyright 2017-2022 The MathJax Consortium
# SPDX-License-Identifier: Apache-2.0
#
# Translated and modified for Go table generation by the mathjax-go authors.
"""Generate Go TeX font tables from the MathJax 3.2.2 TypeScript sources.

The parser is deliberately small and accepts only the literal syntax used by
ts/output/{common,svg}/fonts/tex.  Set MATHJAX_SRC to the MathJax checkout (or
pass --source); the generated files are checked in and have no runtime source
dependency.
"""

from __future__ import annotations

import argparse
import ast
import copy
import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
import re
import sys
from typing import Any


VARIANTS = [
    ("normal", "normal", "Normal"),
    ("bold", "bold", "Bold"),
    ("italic", "italic", "Italic"),
    ("bold-italic", "bold-italic", "BoldItalic"),
    ("double-struck", "double-struck", "DoubleStruck"),
    ("fraktur", "fraktur", "Fraktur"),
    ("bold-fraktur", "fraktur-bold", "BoldFraktur"),
    ("script", "script", "Script"),
    ("bold-script", "script-bold", "BoldScript"),
    ("sans-serif", "sans-serif", "SansSerif"),
    ("bold-sans-serif", "sans-serif-bold", "BoldSansSerif"),
    ("sans-serif-italic", "sans-serif-italic", "SansSerifItalic"),
    ("sans-serif-bold-italic", "sans-serif-bold-italic", "SansSerifBoldItalic"),
    ("monospace", "monospace", "Monospace"),
    ("-smallop", "smallop", "SmallOp"),
    ("-largeop", "largeop", "LargeOp"),
    ("-size3", "tex-size3", "Size3"),
    ("-size4", "tex-size4", "Size4"),
    ("-tex-calligraphic", "tex-calligraphic", "TeXCalligraphic"),
    ("-tex-bold-calligraphic", "tex-calligraphic-bold", "TeXBoldCalligraphic"),
    ("-tex-mathit", "tex-mathit", "TeXMathItalic"),
    ("-tex-oldstyle", "tex-oldstyle", "TeXOldStyle"),
    ("-tex-bold-oldstyle", "tex-oldstyle-bold", "TeXBoldOldStyle"),
    ("-tex-variant", "tex-variant", "TeXVariant"),
]


GENERATED_HEADER = """// Copyright (c) 2018-2022 The MathJax Consortium
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Derived mechanically from MathJax 3.2.2
// ts/output/{common,svg}/fonts/tex.
// Code generated by generate.py; DO NOT EDIT.

package font

"""


@dataclass(frozen=True)
class Number:
    raw: str

    @property
    def integer(self) -> int:
        return int(self.raw, 0)

    @property
    def floating(self) -> float:
        return float(self.raw)


@dataclass(frozen=True)
class Reference:
    name: str


class Parser:
    def __init__(self, text: str, pos: int = 0):
        self.text = text
        self.pos = pos

    def skip(self) -> None:
        while self.pos < len(self.text):
            match = re.match(r"\s+", self.text[self.pos :])
            if match:
                self.pos += match.end()
                continue
            if self.text.startswith("//", self.pos):
                end = self.text.find("\n", self.pos + 2)
                self.pos = len(self.text) if end < 0 else end + 1
                continue
            if self.text.startswith("/*", self.pos):
                end = self.text.find("*/", self.pos + 2)
                if end < 0:
                    raise ValueError("unterminated comment")
                self.pos = end + 2
                continue
            break

    def peek(self) -> str:
        self.skip()
        return self.text[self.pos : self.pos + 1]

    def take(self, value: str) -> None:
        self.skip()
        if not self.text.startswith(value, self.pos):
            raise ValueError(f"expected {value!r} at offset {self.pos}")
        self.pos += len(value)

    def identifier(self) -> str:
        self.skip()
        match = re.match(r"[A-Za-z_$][A-Za-z0-9_$]*", self.text[self.pos :])
        if not match:
            raise ValueError(f"expected identifier at offset {self.pos}")
        self.pos += match.end()
        return match.group(0)

    def number(self) -> Number:
        self.skip()
        match = re.match(
            r"-?(?:0[xX][0-9A-Fa-f]+|(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eE][+-]?\d+)?)",
            self.text[self.pos :],
        )
        if not match:
            raise ValueError(f"expected number at offset {self.pos}")
        self.pos += match.end()
        return Number(match.group(0))

    def string(self) -> str:
        self.skip()
        quote = self.text[self.pos]
        start = self.pos
        self.pos += 1
        escaped = False
        while self.pos < len(self.text):
            char = self.text[self.pos]
            self.pos += 1
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                return ast.literal_eval(self.text[start : self.pos])
        raise ValueError(f"unterminated string at offset {start}")

    def value(self) -> Any:
        self.skip()
        char = self.peek()
        if char == "{":
            return self.object()
        if char == "[":
            return self.array()
        if char in ("'", '"'):
            return self.string()
        if char == "-" or char == "." or char.isdigit():
            return self.number()
        name = self.identifier()
        if name == "true":
            return True
        if name == "false":
            return False
        if name in ("null", "undefined"):
            return None
        return Reference(name)

    def array(self) -> list[Any]:
        values: list[Any] = []
        self.take("[")
        while self.peek() != "]":
            # TypeScript's sparse arrays occur outside this tranche, but
            # accepting holes makes the literal parser deterministic.
            if self.peek() == ",":
                values.append(None)
                self.take(",")
                continue
            values.append(self.value())
            if self.peek() != ",":
                break
            self.take(",")
        self.take("]")
        return values

    def object(self) -> dict[Any, Any]:
        values: dict[Any, Any] = {}
        self.take("{")
        while self.peek() != "}":
            char = self.peek()
            if char in ("'", '"'):
                key: Any = self.string()
            elif char == "-" or char == "." or char.isdigit():
                number = self.number()
                key = number.integer
            else:
                key = self.identifier()
            self.take(":")
            values[key] = self.value()
            if self.peek() != ",":
                break
            self.take(",")
        self.take("}")
        return values


def resolve(value: Any, environment: dict[str, Any]) -> Any:
    if isinstance(value, Reference):
        if value.name not in environment:
            raise ValueError(f"unknown literal reference {value.name}")
        return copy.deepcopy(environment[value.name])
    if isinstance(value, list):
        return [resolve(item, environment) for item in value]
    if isinstance(value, dict):
        return {key: resolve(item, environment) for key, item in value.items()}
    return value


def exported_object(text: str) -> dict[int, Any]:
    match = re.search(r"export\s+const\s+\w+\s*:[^=]+?=\s*", text)
    if not match:
        raise ValueError("exported object was not found")
    value = Parser(text, match.end()).value()
    if not isinstance(value, dict):
        raise ValueError("exported value is not an object")
    return value


def svg_objects(text: str) -> tuple[dict[int, str], dict[int, str]]:
    marker = "AddPaths(font,"
    start = text.find(marker)
    if start < 0:
        return {}, {}
    parser = Parser(text, start + len(marker))
    paths = parser.value()
    if not isinstance(paths, dict):
        raise ValueError("SVG path argument is not an object")
    content: dict[int, str] = {}
    if parser.peek() == ",":
        parser.take(",")
        if parser.peek() == "{":
            content = parser.value()
    return paths, content


def delimiter_object(text: str) -> dict[int, Any]:
    environment: dict[str, Any] = {"V": "V", "H": "H"}
    declaration = re.compile(r"(?:export\s+)?const\s+(\w+)\s*(?::[^=]+)?=\s*")
    delimiters: dict[int, Any] | None = None
    for match in declaration.finditer(text):
        name = match.group(1)
        value = Parser(text, match.end()).value()
        value = resolve(value, environment)
        environment[name] = value
        if name == "delimiters":
            delimiters = value
    if delimiters is None:
        raise ValueError("delimiter map was not found")
    return delimiters


def go_number(number: Number) -> str:
    raw = number.raw
    if raw.startswith("-."):
        return "-0" + raw[1:]
    if raw.startswith("."):
        return "0" + raw
    return raw


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"))


def go_float_slice(values: list[Number]) -> str:
    return "[]float64{" + ", ".join(go_number(value) for value in values) + "}"


def go_int_slice(values: list[Number]) -> str:
    return "[]int{" + ", ".join(str(value.integer) for value in values) + "}"


def go_rune_slice(values: list[Number]) -> str:
    return "[]rune{" + ", ".join(f"0x{value.integer:X}" for value in values) + "}"


def render_metrics(values: list[Any]) -> str:
    if len(values) not in (3, 4):
        raise ValueError(f"unexpected CharData length {len(values)}")
    parts = [
        f"Height: {go_number(values[0])}",
        f"Depth: {go_number(values[1])}",
        f"Width: {go_number(values[2])}",
    ]
    if len(values) == 4:
        options = values[3]
        unknown = set(options) - {"ic", "sk"}
        if unknown:
            raise ValueError(f"unsupported CharOptions: {sorted(unknown)}")
        if "ic" in options:
            parts.extend((f"ItalicCorrection: {go_number(options['ic'])}", "HasItalicCorrection: true"))
        if "sk" in options:
            parts.extend((f"Skew: {go_number(options['sk'])}", "HasSkew: true"))
    return "Metrics{" + ", ".join(parts) + "}"


def write_variant(
    output: Path,
    source_name: str,
    go_name: str,
    metrics: dict[int, list[Any]],
    paths: dict[int, str],
    content: dict[int, str],
) -> None:
    if set(paths) & set(content):
        raise ValueError(f"{source_name}: path and content maps overlap")
    if set(metrics) != set(paths) | set(content):
        missing = sorted(set(metrics) - set(paths) - set(content))
        extra = sorted((set(paths) | set(content)) - set(metrics))
        raise ValueError(f"{source_name}: SVG coverage mismatch missing={missing[:5]} extra={extra[:5]}")
    lines = [GENERATED_HEADER, f"var glyphTable{go_name} = map[rune]glyphData{{\n"]
    for codepoint in sorted(metrics):
        fields = [f"Metrics: {render_metrics(metrics[codepoint])}"]
        if codepoint in paths:
            fields.append(f"Path: {go_string(paths[codepoint])}")
        if codepoint in content:
            fields.append(f"Content: {go_string(content[codepoint])}")
        lines.append(f"\t0x{codepoint:X}: {{{', '.join(fields)}}},\n")
    lines.append("}\n")
    (output / f"data_{source_name.replace('-', '_')}_gen.go").write_text("".join(lines))


def render_delimiter(data: dict[str, Any]) -> str:
    allowed = {"dir", "sizes", "variants", "schar", "stretch", "stretchv", "HDW", "min", "c", "fullExt"}
    unknown = set(data) - allowed
    if unknown:
        raise ValueError(f"unsupported DelimiterData: {sorted(unknown)}")
    direction = {"V": "DirectionVertical", "H": "DirectionHorizontal"}[data["dir"]]
    fields = [f"Direction: {direction}"]
    if "sizes" in data:
        fields.append(f"Sizes: {go_float_slice(data['sizes'])}")
    if "variants" in data:
        fields.append(f"SizeVariants: {go_int_slice(data['variants'])}")
    if "schar" in data:
        fields.append(f"SizeChars: {go_rune_slice(data['schar'])}")
    if "stretch" in data:
        fields.append(f"Stretch: {go_rune_slice(data['stretch'])}")
    if "stretchv" in data:
        fields.append(f"StretchVariants: {go_int_slice(data['stretchv'])}")
    if "HDW" in data:
        values = data["HDW"]
        fields.extend((
            "HDW: [3]float64{" + ", ".join(go_number(value) for value in values) + "}",
            "HasHDW: true",
        ))
    if "min" in data:
        fields.extend((f"Min: {go_number(data['min'])}", "HasMin: true"))
    if "c" in data:
        fields.extend((f"Alias: 0x{data['c'].integer:X}", "HasAlias: true"))
    if "fullExt" in data:
        values = data["fullExt"]
        fields.extend((
            "FullExt: [2]float64{" + ", ".join(go_number(value) for value in values) + "}",
            "HasFullExt: true",
        ))
    return "Delimiter{" + ", ".join(fields) + "}"


def write_delimiters(output: Path, delimiters: dict[int, dict[str, Any]]) -> None:
    lines = [GENERATED_HEADER, "var delimiterTable = map[rune]Delimiter{\n"]
    for codepoint in sorted(delimiters):
        lines.append(f"\t0x{codepoint:X}: {render_delimiter(delimiters[codepoint])},\n")
    lines.append("}\n")
    (output / "data_delimiters_gen.go").write_text("".join(lines))


def source_hash(files: list[Path], root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted(files):
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def write_registry(output: Path, hashes: tuple[str, str, str]) -> None:
    lines = [GENERATED_HEADER, "var glyphTables = map[Variant]map[rune]glyphData{\n"]
    for _, _, go_name in VARIANTS:
        lines.append(f"\t{go_name}: glyphTable{go_name},\n")
    lines.extend((
        "}\n\n",
        "// Source hashes cover sorted relative names, NUL, exact source bytes, and NUL.\n",
        f'const CommonSourceSHA256 = "{hashes[0]}"\n',
        f'const SVGSourceSHA256 = "{hashes[1]}"\n',
        f'const DelimiterSourceSHA256 = "{hashes[2]}"\n',
    ))
    (output / "data_registry_gen.go").write_text("".join(lines))


def find_source(argument: str | None, output: Path) -> Path:
    candidates: list[Path] = []
    if argument:
        candidates.append(Path(argument))
    if os.environ.get("MATHJAX_SRC"):
        candidates.append(Path(os.environ["MATHJAX_SRC"]))
    candidates.append((output / "../../../../work/mathjax-src-3.2.2").resolve())
    for candidate in candidates:
        if (candidate / "ts/output/common/fonts/tex/normal.ts").is_file():
            return candidate / "ts/output"
        if (candidate / "common/fonts/tex/normal.ts").is_file():
            return candidate
    raise SystemExit("MathJax 3.2.2 source not found; pass --source or set MATHJAX_SRC")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", help="MathJax checkout root or its ts/output directory")
    parser.add_argument("--output", help="generated package directory")
    args = parser.parse_args()

    output = Path(args.output).resolve() if args.output else Path(__file__).resolve().parent
    source = find_source(args.source, output)
    common_dir = source / "common/fonts/tex"
    svg_dir = source / "svg/fonts/tex"

    for stale in output.glob("data_*_gen.go"):
        stale.unlink()

    common_files: list[Path] = []
    svg_files: list[Path] = []
    for _, source_name, go_name in VARIANTS:
        common_path = common_dir / f"{source_name}.ts"
        svg_path = svg_dir / f"{source_name}.ts"
        common_files.append(common_path)
        svg_files.append(svg_path)
        metrics = exported_object(common_path.read_text())
        paths, content = svg_objects(svg_path.read_text())
        write_variant(output, source_name, go_name, metrics, paths, content)

    delimiter_path = common_dir / "delimiters.ts"
    delimiters = delimiter_object(delimiter_path.read_text())
    write_delimiters(output, delimiters)
    write_registry(
        output,
        (
            source_hash(common_files, source),
            source_hash(svg_files, source),
            source_hash([delimiter_path], source),
        ),
    )
    print(f"generated {sum(len(exported_object(path.read_text())) for path in common_files)} glyphs and {len(delimiters)} delimiters", file=sys.stderr)


if __name__ == "__main__":
    main()
