// SPDX-License-Identifier: Apache-2.0
// node --jitless testdata/generate_dcases_displaystyle.cjs PINNED_ASSETS NEW_OUTPUT
// All SVGs come from fresh frozen MathJax 3.2.2 contexts. This never invokes Go.
'use strict';
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const zlib = require('node:zlib'), crypto = require('node:crypto'), assert = require('node:assert/strict');
const PIN = 'ad8f5c21cb810236551da8c6512ba733e67357ee';
const UNION = '6e2be76864e694bbd8756e27eebe0a9abdf02c4a0cea6c79add36c97dd46d4ae';
const ASSETS = {
  'polyfills.js': '7fe1d048c78b0e09854c1259f7413868a51cc8f0c822489eb1ac36ae6c85ce01',
  'mathjax.js': 'cbbc1051a1f8abb1a181b6aa0fe927c020e3631ca630d19f52d9abb65b5ee869',
  'setup.js': 'a52cb0bbabfbd7796b9fedd793b9386c474e3123e788ee151cbe47ca1fa6e881',
};
const FILES = ['dcases_displaystyle_mathjax_3_2_2.json.gz', 'dcases_displaystyle_residuals.json.gz', 'dcases_displaystyle_observations.json.gz'];
const sha = b => crypto.createHash('sha256').update(b).digest('hex');
const key = r => JSON.stringify([r.tex, r.display]);
const encode = value => zlib.gzipSync(JSON.stringify(value, null, 2) + '\n', {level:9});
// Hook body preserved from observe180.cjs; snapshots are read before the original EndTable call.
const OBSERVER = new vm.Script(`(()=>{const P=MathJax._.input.tex.base.BaseItems.ArrayItem.prototype;const original=P.EndTable;
 P.EndTable=function(){const event={method:'ArrayItem.EndTable',definition:JSON.parse(JSON.stringify(this.arraydef)),open:this.getProperty('open')||null,close:this.getProperty('close')||null,casesEnv:this.getProperty('casesEnv')||null,rows:this.table.length};events.push(event);return original.apply(this,arguments);};})()`);
const CONVERT = new vm.Script('({svg:adaptor.innerHTML(html.convert(request.tex,{display:request.display,em:16,ex:8}))})');
function main() {
  const args = process.argv.slice(2); assert.equal(args.length, 2, 'Pass PINNED_ASSETS NEW_OUTPUT');
  const assets = path.resolve(args[0]), output = path.resolve(args[1]);
  assert(!fs.existsSync(output), 'Output directory must be new');
  const scripts = Object.entries(ASSETS).map(([name, digest]) => {
    const bytes = fs.readFileSync(path.join(assets, name)); assert.equal(sha(bytes), digest, name);
    return new vm.Script(bytes.toString(), {filename:name});
  });
  const sourceBytes = FILES.map(name => fs.readFileSync(path.join(__dirname, name)));
  const docs = sourceBytes.map(bytes => JSON.parse(zlib.gunzipSync(bytes)));
  assert.equal(docs[0].cases.length, 500); assert.equal(docs[1].cases.length, 8);
  assert.equal(docs[2].sourcePin, PIN); assert.deepEqual(docs[2].pins, ASSETS); assert.equal(docs[2].cases.length, 144);
  const originals = new Map();
  for (const doc of docs.slice(0, 2)) {
    assert.equal(doc.mathjaxGitCommit, PIN); assert.equal(doc.sourceUnionSHA256, UNION);
    for (const row of doc.cases) {
      assert.equal(typeof row.tex, 'string'); assert.equal(typeof row.display, 'boolean');
      assert(!originals.has(key(row))); originals.set(key(row), row.original);
      assert.deepEqual(Object.keys(row.original), ['svg']);
    }
  }
  assert.equal(originals.size, 508);
  const passiveKeys = new Set();
  for (const row of docs[2].cases) {
    assert(!passiveKeys.has(key(row))); passiveKeys.add(key(row));
    assert.deepEqual(row.original, originals.get(key(row))); assert.deepEqual(row.observed.output, row.original);
  }
  fs.mkdirSync(output, {recursive:true});
  let conversions = 0;
  function render(request, observed) {
    const context = vm.createContext({console, request, events:[]}); context.globalThis = context;
    for (const script of scripts) script.runInContext(context, {timeout:10000});
    if (observed) OBSERVER.runInContext(context, {timeout:10000});
    const result = CONVERT.runInContext(context, {timeout:10000}); conversions++;
    return JSON.parse(JSON.stringify({output:result, events:context.events}));
  }
  try {
    const fresh = [];
    for (const doc of docs.slice(0, 2)) {
      const cases = doc.cases.map(row => {
        const result = render(row, false); assert.deepEqual(result.output, row.original); assert.deepEqual(result.events, []);
        return {...row, original:result.output};
      });
      fresh.push({...doc, cases});
    }
    const cases = docs[2].cases.map(row => {
      const plain = render(row, false), observed = render(row, true);
      assert.deepEqual(plain.output, row.original); assert.deepEqual(plain.events, []);
      assert.deepEqual(observed, row.observed); assert.deepEqual(observed.output, row.original);
      return {...row, original:plain.output, observed};
    });
    fresh.push({...docs[2], cases});
    const receipts = {};
    for (let i = 0; i < FILES.length; i++) {
      assert.deepEqual(fresh[i], docs[i]);
      const bytes = encode(fresh[i]); assert(bytes.equals(sourceBytes[i]), 'Regenerated bytes differ: ' + FILES[i]);
      fs.writeFileSync(path.join(output, FILES[i]), bytes, {flag:'wx'});
      receipts[FILES[i]] = {sha256:sha(bytes), byteIdentical:true, completeObjectsEqual:true};
    }
    const receipt = {status:'PASS original-only complete-object and byte-identical regeneration', mathjaxGitCommit:PIN,
      sourceUnionSHA256:UNION, assets:ASSETS, completeOriginalSVGs:508, matchedOriginalSVGs:500, heldOriginalSVGs:8,
      passiveExistingInputs:144, passiveFreshConversions:288, conversions, originalRuntimeExceptions:0,
      files:receipts, node:process.version, generatorSHA256:sha(fs.readFileSync(__filename)), noGo:true};
    fs.writeFileSync(path.join(output, 'dcases_displaystyle_regeneration.json'), JSON.stringify(receipt, null, 2) + '\n', {flag:'wx'});
    console.log(JSON.stringify(receipt));
  } catch (error) {
    fs.writeFileSync(path.join(output, 'failed-regeneration.json'), JSON.stringify({conversions, name:error.name, message:error.message, stack:error.stack}, null, 2) + '\n', {flag:'wx'});
    throw error;
  }
}
module.exports = {encode};
if (require.main === module) main();
